export const ids = {
  transportButton: "anp:transport:create",
  transportModal: "anp:transport:modal",
  transportSecondary: "anp:transport:secondary",
  transportPickup: "anp:transport:pickup",
  transportDetainee: "anp:transport:detainee",
  transportEditButton: "anp:transport:edit",
  transportEditModalPrefix: "anp:transport:edit-modal:",

  vizitaButton: "anp:vizita:create",
  vizitaModal: "anp:vizita:modal",
  vizitaSecondary: "anp:vizita:secondary",
  vizitaVisitor: "anp:vizita:visitor",
  vizitaDetainee: "anp:vizita:detainee",
  vizitaDateTime: "anp:vizita:datetime",
  vizitaEditButton: "anp:vizita:edit",
  vizitaEditModalPrefix: "anp:vizita:edit-modal:",

  carceraButton: "anp:carcera:create",
  carceraModal: "anp:carcera:modal",
  carceraDetainee: "anp:carcera:detainee",
  carceraMonths: "anp:carcera:months",
  carceraReason: "anp:carcera:reason",
  carceraEditButton: "anp:carcera:edit",
  carceraEditModalPrefix: "anp:carcera:edit-modal:",
  carceraApprove: "anp:carcera:approve",
  carceraReject: "anp:carcera:reject",

  invatatStartButton: "anp:invatat:start",
  invatatConfirmReadButton: "anp:invatat:confirm-read",
  invatatAnswerButtonPrefix: "anp:invatat:answer:",
  invatatAnswerModalPrefix: "anp:invatat:answer-modal:",
  invatatAnswerField: "anp:invatat:answer-field",
} as const;
